product_expert_task:
  description: |
    Answer the user's product-related query using the knowledge base:

    1. Search the knowledge base file for relevant information about: {message}
    2. If found:
       - Provide accurate information from the knowledge base
       - Be concise and clear in your response
    3. If not found:
       - Inform the user that the information is not in the knowledge base
       - Suggest asking about topics that are covered in the knowledge base

    Message: {message}
    Previous conversation: {conversation_history}
  expected_output: |
    A response that either:
    - Provides accurate product information found in the knowledge base
    - OR clearly explains that the information is not available in the knowledge base
  agent: product_expert_agent
